// <auto-generated />
using System;
using ApartmentManagementSystem.EF.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DbMigrationTools.Migrations
{
    [DbContext(typeof(ApartmentManagementDbContext))]
    [Migration("20251109034623_UpdateFeeConfiguration")]
    partial class UpdateFeeConfiguration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ApartmentManagementSystem.EF.Context.Apartment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ApartmentBuildingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("Area")
                        .HasColumnType("float");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedByUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Floor")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdatedByUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ApartmentBuildingId");

                    b.ToTable("Apartments");
                });

            modelBuilder.Entity("ApartmentManagementSystem.EF.Context.ApartmentBuilding", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ApartmentBuildingImgUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactPhone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedByUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CurrencyUnit")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OwnerUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdatedByUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("ApartmentBuildings");
                });

            modelBuilder.Entity("ApartmentManagementSystem.EF.Context.ApartmentBuildingImage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ApartmentBuildingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Src")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ApartmentBuildingId");

                    b.ToTable("ApartmentBuildingImage");
                });

            modelBuilder.Entity("ApartmentManagementSystem.EF.Context.BillingCycleSetting", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ApartmentBuildingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ClosingDayOfMonth")
                        .HasColumnType("int");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedByUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("PaymentDueDate")
                        .HasColumnType("int");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdatedByUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ApartmentBuildingId")
                        .IsUnique();

                    b.ToTable("BillingCycleSettings");
                });

            modelBuilder.Entity("ApartmentManagementSystem.EF.Context.FeeDetail", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<double?>("Consumption")
                        .HasColumnType("float");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedByUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<double?>("CurrentReading")
                        .HasColumnType("float");

                    b.Property<DateTime?>("CurrentReadingDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("FeeNoticeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("FeeTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("GrossCost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<double?>("PreviousReading")
                        .HasColumnType("float");

                    b.Property<DateTime?>("PreviousReadingDate")
                        .HasColumnType("datetime2");

                    b.Property<double?>("Proration")
                        .HasColumnType("float");

                    b.Property<decimal>("SubTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdatedByUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("VATCost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<float>("VATRate")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("FeeNoticeId");

                    b.HasIndex("FeeTypeId");

                    b.ToTable("FeeDetails");
                });

            modelBuilder.Entity("ApartmentManagementSystem.EF.Context.FeeDetailTier", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("Consumption")
                        .HasColumnType("float");

                    b.Property<double>("ConsumptionEnd")
                        .HasColumnType("float");

                    b.Property<double>("ConsumptionEndOriginal")
                        .HasColumnType("float");

                    b.Property<double>("ConsumptionStart")
                        .HasColumnType("float");

                    b.Property<double>("ConsumptionStartOriginal")
                        .HasColumnType("float");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedByUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("FeeDetailId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("TierOrder")
                        .HasColumnType("int");

                    b.Property<string>("UnitName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("UnitRate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdatedByUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("FeeDetailId");

                    b.ToTable("FeeDetailTier");
                });

            modelBuilder.Entity("ApartmentManagementSystem.EF.Context.FeeNotice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ApartmentBuildingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ApartmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BillingCycle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedByUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("IssueDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PaymentStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdatedByUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ApartmentId");

                    b.ToTable("FeeNotices");
                });

            modelBuilder.Entity("ApartmentManagementSystem.EF.Context.FeeRateConfig", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ApartmentBuildingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedByUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("FeeTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UnitName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdatedByUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<float>("VATRate")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("FeeTypeId");

                    b.ToTable("FeeRateConfigs");
                });

            modelBuilder.Entity("ApartmentManagementSystem.EF.Context.FeeTier", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("ConsumptionEnd")
                        .HasColumnType("float");

                    b.Property<double>("ConsumptionStart")
                        .HasColumnType("float");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedByUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("FeeRateConfigId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("TierOrder")
                        .HasColumnType("int");

                    b.Property<string>("UnitName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("UnitRate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdatedByUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("FeeRateConfigId");

                    b.ToTable("FeeTiers");
                });

            modelBuilder.Entity("ApartmentManagementSystem.EF.Context.FeeType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ApartmentBuildingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CalculationType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedByUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("DefaultRate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<float>("DefaultVATRate")
                        .HasColumnType("real");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsVATApplicable")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdatedByUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ApartmentBuildingId");

                    b.ToTable("FeeTypes");
                });

            modelBuilder.Entity("ApartmentManagementSystem.EF.Context.ParkingRegistration", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ApartmentBuildingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ApartmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedByUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdatedByUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("VehicleDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VehicleNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VehicleType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ApartmentId");

                    b.ToTable("ParkingRegistrations");
                });

            modelBuilder.Entity("ApartmentManagementSystem.EF.Context.QuantityRateConfig", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ApartmentBuildingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedByUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("FeeTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("ItemType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("UnitRate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdatedByUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("FeeTypeId");

                    b.ToTable("QuantityRateConfig");
                });

            modelBuilder.Entity("ApartmentManagementSystem.EF.Context.UtilityReading", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ApartmentBuildingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ApartmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedByUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<double>("CurrentReading")
                        .HasColumnType("float");

                    b.Property<Guid>("FeeTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ReadingDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdatedByUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ApartmentId");

                    b.HasIndex("FeeTypeId");

                    b.ToTable("UtilityReadings");
                });

            modelBuilder.Entity("ApartmentManagementSystem.EF.Context.Apartment", b =>
                {
                    b.HasOne("ApartmentManagementSystem.EF.Context.ApartmentBuilding", "ApartmentBuilding")
                        .WithMany("Apartments")
                        .HasForeignKey("ApartmentBuildingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApartmentBuilding");
                });

            modelBuilder.Entity("ApartmentManagementSystem.EF.Context.ApartmentBuildingImage", b =>
                {
                    b.HasOne("ApartmentManagementSystem.EF.Context.ApartmentBuilding", "ApartmentBuilding")
                        .WithMany("Images")
                        .HasForeignKey("ApartmentBuildingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApartmentBuilding");
                });

            modelBuilder.Entity("ApartmentManagementSystem.EF.Context.BillingCycleSetting", b =>
                {
                    b.HasOne("ApartmentManagementSystem.EF.Context.ApartmentBuilding", "ApartmentBuilding")
                        .WithOne("BillingCycleSetting")
                        .HasForeignKey("ApartmentManagementSystem.EF.Context.BillingCycleSetting", "ApartmentBuildingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApartmentBuilding");
                });

            modelBuilder.Entity("ApartmentManagementSystem.EF.Context.FeeDetail", b =>
                {
                    b.HasOne("ApartmentManagementSystem.EF.Context.FeeNotice", "FeeNotice")
                        .WithMany("FeeDetails")
                        .HasForeignKey("FeeNoticeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ApartmentManagementSystem.EF.Context.FeeType", "FeeType")
                        .WithMany("FeeDetails")
                        .HasForeignKey("FeeTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FeeNotice");

                    b.Navigation("FeeType");
                });

            modelBuilder.Entity("ApartmentManagementSystem.EF.Context.FeeDetailTier", b =>
                {
                    b.HasOne("ApartmentManagementSystem.EF.Context.FeeDetail", "FeeDetail")
                        .WithMany("FeeDetailTiers")
                        .HasForeignKey("FeeDetailId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FeeDetail");
                });

            modelBuilder.Entity("ApartmentManagementSystem.EF.Context.FeeNotice", b =>
                {
                    b.HasOne("ApartmentManagementSystem.EF.Context.Apartment", "Apartment")
                        .WithMany("FeeNotices")
                        .HasForeignKey("ApartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Apartment");
                });

            modelBuilder.Entity("ApartmentManagementSystem.EF.Context.FeeRateConfig", b =>
                {
                    b.HasOne("ApartmentManagementSystem.EF.Context.FeeType", "FeeType")
                        .WithMany("FeeRateConfigs")
                        .HasForeignKey("FeeTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FeeType");
                });

            modelBuilder.Entity("ApartmentManagementSystem.EF.Context.FeeTier", b =>
                {
                    b.HasOne("ApartmentManagementSystem.EF.Context.FeeRateConfig", "FeeRateConfig")
                        .WithMany("FeeTiers")
                        .HasForeignKey("FeeRateConfigId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FeeRateConfig");
                });

            modelBuilder.Entity("ApartmentManagementSystem.EF.Context.FeeType", b =>
                {
                    b.HasOne("ApartmentManagementSystem.EF.Context.ApartmentBuilding", "ApartmentBuilding")
                        .WithMany("FeeTypes")
                        .HasForeignKey("ApartmentBuildingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApartmentBuilding");
                });

            modelBuilder.Entity("ApartmentManagementSystem.EF.Context.ParkingRegistration", b =>
                {
                    b.HasOne("ApartmentManagementSystem.EF.Context.Apartment", "Apartment")
                        .WithMany("ParkingRegistrations")
                        .HasForeignKey("ApartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Apartment");
                });

            modelBuilder.Entity("ApartmentManagementSystem.EF.Context.QuantityRateConfig", b =>
                {
                    b.HasOne("ApartmentManagementSystem.EF.Context.FeeType", "FeeType")
                        .WithMany("QuantityRateConfigs")
                        .HasForeignKey("FeeTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FeeType");
                });

            modelBuilder.Entity("ApartmentManagementSystem.EF.Context.UtilityReading", b =>
                {
                    b.HasOne("ApartmentManagementSystem.EF.Context.Apartment", "Apartment")
                        .WithMany("UtilityReadings")
                        .HasForeignKey("ApartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ApartmentManagementSystem.EF.Context.FeeType", "FeeType")
                        .WithMany("UtilityReadings")
                        .HasForeignKey("FeeTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Apartment");

                    b.Navigation("FeeType");
                });

            modelBuilder.Entity("ApartmentManagementSystem.EF.Context.Apartment", b =>
                {
                    b.Navigation("FeeNotices");

                    b.Navigation("ParkingRegistrations");

                    b.Navigation("UtilityReadings");
                });

            modelBuilder.Entity("ApartmentManagementSystem.EF.Context.ApartmentBuilding", b =>
                {
                    b.Navigation("Apartments");

                    b.Navigation("BillingCycleSetting")
                        .IsRequired();

                    b.Navigation("FeeTypes");

                    b.Navigation("Images");
                });

            modelBuilder.Entity("ApartmentManagementSystem.EF.Context.FeeDetail", b =>
                {
                    b.Navigation("FeeDetailTiers");
                });

            modelBuilder.Entity("ApartmentManagementSystem.EF.Context.FeeNotice", b =>
                {
                    b.Navigation("FeeDetails");
                });

            modelBuilder.Entity("ApartmentManagementSystem.EF.Context.FeeRateConfig", b =>
                {
                    b.Navigation("FeeTiers");
                });

            modelBuilder.Entity("ApartmentManagementSystem.EF.Context.FeeType", b =>
                {
                    b.Navigation("FeeDetails");

                    b.Navigation("FeeRateConfigs");

                    b.Navigation("QuantityRateConfigs");

                    b.Navigation("UtilityReadings");
                });
#pragma warning restore 612, 618
        }
    }
}
