// <auto-generated />
using System;
using ApartmentManagementSystem.EF.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DbMigrationTools.Migrations
{
    [DbContext(typeof(ApartmentManagementDbContext))]
    [Migration("20260117055624_ValidateFields")]
    partial class ValidateFields
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ApartmentManagementSystem.EF.Context.Announcement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ApartmentBuildingId")
                        .HasColumnType("uuid");

                    b.Property<string>("ApartmentIds")
                        .HasColumnType("text");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("CreatedByUserDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("CreatedByUserName")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsAll")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("PublishDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("character varying(25)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<string>("UpdatedByUserDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UpdatedByUserName")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ApartmentBuildingId");

                    b.ToTable("Announcements");
                });

            modelBuilder.Entity("ApartmentManagementSystem.EF.Context.Apartment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ApartmentBuildingId")
                        .HasColumnType("uuid");

                    b.Property<double>("Area")
                        .HasColumnType("double precision");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("CreatedByUserDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("CreatedByUserName")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Floor")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<string>("UpdatedByUserDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UpdatedByUserName")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ApartmentBuildingId");

                    b.ToTable("Apartments");
                });

            modelBuilder.Entity("ApartmentManagementSystem.EF.Context.ApartmentBuilding", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("ApartmentBuildingImgUrl")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("ContactEmail")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("ContactPhone")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("CreatedByUserDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("CreatedByUserName")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CurrencyUnit")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("character varying(25)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("OwnerUserName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("character varying(25)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<string>("UpdatedByUserDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UpdatedByUserName")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("ApartmentBuildings");
                });

            modelBuilder.Entity("ApartmentManagementSystem.EF.Context.ApartmentResident", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ApartmentId")
                        .HasColumnType("uuid");

                    b.Property<string>("MemberType")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("character varying(25)");

                    b.Property<Guid>("ResidentId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ApartmentId");

                    b.HasIndex("ResidentId");

                    b.ToTable("ApartmentResidents");
                });

            modelBuilder.Entity("ApartmentManagementSystem.EF.Context.BillingCycleSetting", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ApartmentBuildingId")
                        .HasColumnType("uuid");

                    b.Property<int>("ClosingDayOfMonth")
                        .HasColumnType("integer");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("CreatedByUserDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("CreatedByUserName")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("PaymentDueDate")
                        .HasColumnType("integer");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<string>("UpdatedByUserDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UpdatedByUserName")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ApartmentBuildingId")
                        .IsUnique();

                    b.ToTable("BillingCycleSettings");
                });

            modelBuilder.Entity("ApartmentManagementSystem.EF.Context.FeeDetail", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double?>("Consumption")
                        .HasColumnType("double precision");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("CreatedByUserDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("CreatedByUserName")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double?>("CurrentReading")
                        .HasColumnType("double precision");

                    b.Property<DateTime?>("CurrentReadingDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("FeeNoticeId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("FeeTypeId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("NetCost")
                        .HasColumnType("numeric");

                    b.Property<double?>("PreviousReading")
                        .HasColumnType("double precision");

                    b.Property<DateTime?>("PreviousReadingDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double?>("Proration")
                        .HasColumnType("double precision");

                    b.Property<decimal>("SubTotal")
                        .HasColumnType("numeric");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<string>("UpdatedByUserDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UpdatedByUserName")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("VATCost")
                        .HasColumnType("numeric");

                    b.Property<float>("VATRate")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("FeeNoticeId");

                    b.HasIndex("FeeTypeId");

                    b.ToTable("FeeDetails");
                });

            modelBuilder.Entity("ApartmentManagementSystem.EF.Context.FeeDetailTier", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double>("Consumption")
                        .HasColumnType("double precision");

                    b.Property<double>("ConsumptionEnd")
                        .HasColumnType("double precision");

                    b.Property<double>("ConsumptionEndOriginal")
                        .HasColumnType("double precision");

                    b.Property<double>("ConsumptionStart")
                        .HasColumnType("double precision");

                    b.Property<double>("ConsumptionStartOriginal")
                        .HasColumnType("double precision");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("CreatedByUserDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("CreatedByUserName")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("FeeDetailId")
                        .HasColumnType("uuid");

                    b.Property<int>("TierOrder")
                        .HasColumnType("integer");

                    b.Property<string>("UnitName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("UnitRate")
                        .HasColumnType("numeric");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<string>("UpdatedByUserDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UpdatedByUserName")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("FeeDetailId");

                    b.ToTable("FeeDetailTier");
                });

            modelBuilder.Entity("ApartmentManagementSystem.EF.Context.FeeNotice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ApartmentBuildingId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ApartmentId")
                        .HasColumnType("uuid");

                    b.Property<string>("BillingCycle")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("CreatedByUserDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("CreatedByUserName")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("IssueDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PaymentStatus")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("character varying(25)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("character varying(25)");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("numeric");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<string>("UpdatedByUserDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UpdatedByUserName")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ApartmentId");

                    b.ToTable("FeeNotices");
                });

            modelBuilder.Entity("ApartmentManagementSystem.EF.Context.FeeRateConfig", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ApartmentBuildingId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ApplyDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("CreatedByUserDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("CreatedByUserName")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("FeeTypeId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<float?>("OtherRate")
                        .HasColumnType("real");

                    b.Property<string>("UnitName")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("character varying(25)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<string>("UpdatedByUserDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UpdatedByUserName")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<float>("VATRate")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("FeeTypeId");

                    b.ToTable("FeeRateConfigs");
                });

            modelBuilder.Entity("ApartmentManagementSystem.EF.Context.FeeTier", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double>("ConsumptionEnd")
                        .HasColumnType("double precision");

                    b.Property<double>("ConsumptionStart")
                        .HasColumnType("double precision");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("CreatedByUserDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("CreatedByUserName")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("FeeRateConfigId")
                        .HasColumnType("uuid");

                    b.Property<int>("TierOrder")
                        .HasColumnType("integer");

                    b.Property<decimal>("UnitRate")
                        .HasColumnType("numeric");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<string>("UpdatedByUserDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UpdatedByUserName")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("FeeRateConfigId");

                    b.ToTable("FeeTiers");
                });

            modelBuilder.Entity("ApartmentManagementSystem.EF.Context.FeeType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ApartmentBuildingId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ApplyDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CalculationType")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("character varying(25)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("CreatedByUserDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("CreatedByUserName")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("DefaultRate")
                        .HasColumnType("numeric");

                    b.Property<float>("DefaultVATRate")
                        .HasColumnType("real");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsVATApplicable")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<string>("UpdatedByUserDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UpdatedByUserName")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ApartmentBuildingId");

                    b.ToTable("FeeTypes");
                });

            modelBuilder.Entity("ApartmentManagementSystem.EF.Context.FileAttachment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AnnouncementId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ApartmentBuildingId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<Guid?>("FeedbackId")
                        .HasColumnType("uuid");

                    b.Property<string>("FileType")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("character varying(25)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<Guid?>("RequestId")
                        .HasColumnType("uuid");

                    b.Property<string>("Src")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.HasIndex("AnnouncementId");

                    b.HasIndex("ApartmentBuildingId");

                    b.HasIndex("FeedbackId");

                    b.HasIndex("RequestId");

                    b.ToTable("FileAttachments");
                });

            modelBuilder.Entity("ApartmentManagementSystem.EF.Context.ParkingRegistration", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ApartmentBuildingId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ApartmentId")
                        .HasColumnType("uuid");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("CreatedByUserDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("CreatedByUserName")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<string>("UpdatedByUserDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UpdatedByUserName")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("VehicleDescription")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("VehicleNumber")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("VehicleType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("ApartmentId");

                    b.ToTable("ParkingRegistrations");
                });

            modelBuilder.Entity("ApartmentManagementSystem.EF.Context.QuantityRateConfig", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ApartmentBuildingId")
                        .HasColumnType("uuid");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("CreatedByUserDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("CreatedByUserName")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("FeeTypeId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("ItemType")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<decimal>("UnitRate")
                        .HasColumnType("numeric");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<string>("UpdatedByUserDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UpdatedByUserName")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("FeeTypeId");

                    b.ToTable("QuantityRateConfig");
                });

            modelBuilder.Entity("ApartmentManagementSystem.EF.Context.Request", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ApartmentBuildingId")
                        .HasColumnType("uuid");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("CreatedByUserDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("CreatedByUserName")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CurrentHandlerId")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int?>("Rate")
                        .HasColumnType("integer");

                    b.Property<string>("RequestType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("ResidentId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("character varying(25)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<string>("UpdatedByUserDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UpdatedByUserName")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ApartmentBuildingId");

                    b.ToTable("Requests");
                });

            modelBuilder.Entity("ApartmentManagementSystem.EF.Context.RequestHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<Guid>("ApartmentBuildingId")
                        .HasColumnType("uuid");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("CreatedByUserDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("CreatedByUserName")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NewStatus")
                        .HasMaxLength(25)
                        .HasColumnType("character varying(25)");

                    b.Property<string>("NewUserAssignId")
                        .HasColumnType("text");

                    b.Property<string>("Note")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("OldStatus")
                        .HasMaxLength(25)
                        .HasColumnType("character varying(25)");

                    b.Property<Guid>("RequestId")
                        .HasColumnType("uuid");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<string>("UpdatedByUserDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UpdatedByUserName")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("RequestId");

                    b.ToTable("RequestHistory");
                });

            modelBuilder.Entity("ApartmentManagementSystem.EF.Context.Resident", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ApartmentBuildingId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("BrithDay")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("CreatedByUserDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("CreatedByUserName")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("IdentityNumber")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<string>("UpdatedByUserDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UpdatedByUserName")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ApartmentBuildingId");

                    b.ToTable("Residents");
                });

            modelBuilder.Entity("ApartmentManagementSystem.EF.Context.UtilityReading", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ApartmentBuildingId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ApartmentId")
                        .HasColumnType("uuid");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("CreatedByUserDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("CreatedByUserName")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("CurrentReading")
                        .HasColumnType("double precision");

                    b.Property<Guid>("FeeTypeId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ReadingDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<string>("UpdatedByUserDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UpdatedByUserName")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ApartmentId");

                    b.HasIndex("FeeTypeId");

                    b.ToTable("UtilityReadings");
                });

            modelBuilder.Entity("ApartmentManagementSystem.EF.Context.Announcement", b =>
                {
                    b.HasOne("ApartmentManagementSystem.EF.Context.ApartmentBuilding", "ApartmentBuilding")
                        .WithMany("Announcements")
                        .HasForeignKey("ApartmentBuildingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApartmentBuilding");
                });

            modelBuilder.Entity("ApartmentManagementSystem.EF.Context.Apartment", b =>
                {
                    b.HasOne("ApartmentManagementSystem.EF.Context.ApartmentBuilding", "ApartmentBuilding")
                        .WithMany("Apartments")
                        .HasForeignKey("ApartmentBuildingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApartmentBuilding");
                });

            modelBuilder.Entity("ApartmentManagementSystem.EF.Context.ApartmentResident", b =>
                {
                    b.HasOne("ApartmentManagementSystem.EF.Context.Apartment", "Apartment")
                        .WithMany("ApartmentResidents")
                        .HasForeignKey("ApartmentId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("ApartmentManagementSystem.EF.Context.Resident", "Resident")
                        .WithMany("ApartmentResidents")
                        .HasForeignKey("ResidentId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Apartment");

                    b.Navigation("Resident");
                });

            modelBuilder.Entity("ApartmentManagementSystem.EF.Context.BillingCycleSetting", b =>
                {
                    b.HasOne("ApartmentManagementSystem.EF.Context.ApartmentBuilding", "ApartmentBuilding")
                        .WithOne("BillingCycleSetting")
                        .HasForeignKey("ApartmentManagementSystem.EF.Context.BillingCycleSetting", "ApartmentBuildingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApartmentBuilding");
                });

            modelBuilder.Entity("ApartmentManagementSystem.EF.Context.FeeDetail", b =>
                {
                    b.HasOne("ApartmentManagementSystem.EF.Context.FeeNotice", "FeeNotice")
                        .WithMany("FeeDetails")
                        .HasForeignKey("FeeNoticeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ApartmentManagementSystem.EF.Context.FeeType", "FeeType")
                        .WithMany("FeeDetails")
                        .HasForeignKey("FeeTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FeeNotice");

                    b.Navigation("FeeType");
                });

            modelBuilder.Entity("ApartmentManagementSystem.EF.Context.FeeDetailTier", b =>
                {
                    b.HasOne("ApartmentManagementSystem.EF.Context.FeeDetail", "FeeDetail")
                        .WithMany("FeeDetailTiers")
                        .HasForeignKey("FeeDetailId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FeeDetail");
                });

            modelBuilder.Entity("ApartmentManagementSystem.EF.Context.FeeNotice", b =>
                {
                    b.HasOne("ApartmentManagementSystem.EF.Context.Apartment", "Apartment")
                        .WithMany("FeeNotices")
                        .HasForeignKey("ApartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Apartment");
                });

            modelBuilder.Entity("ApartmentManagementSystem.EF.Context.FeeRateConfig", b =>
                {
                    b.HasOne("ApartmentManagementSystem.EF.Context.FeeType", "FeeType")
                        .WithMany("FeeRateConfigs")
                        .HasForeignKey("FeeTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FeeType");
                });

            modelBuilder.Entity("ApartmentManagementSystem.EF.Context.FeeTier", b =>
                {
                    b.HasOne("ApartmentManagementSystem.EF.Context.FeeRateConfig", "FeeRateConfig")
                        .WithMany("FeeTiers")
                        .HasForeignKey("FeeRateConfigId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FeeRateConfig");
                });

            modelBuilder.Entity("ApartmentManagementSystem.EF.Context.FeeType", b =>
                {
                    b.HasOne("ApartmentManagementSystem.EF.Context.ApartmentBuilding", "ApartmentBuilding")
                        .WithMany("FeeTypes")
                        .HasForeignKey("ApartmentBuildingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApartmentBuilding");
                });

            modelBuilder.Entity("ApartmentManagementSystem.EF.Context.FileAttachment", b =>
                {
                    b.HasOne("ApartmentManagementSystem.EF.Context.Announcement", "Announcement")
                        .WithMany("Files")
                        .HasForeignKey("AnnouncementId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("ApartmentManagementSystem.EF.Context.ApartmentBuilding", "ApartmentBuilding")
                        .WithMany("Files")
                        .HasForeignKey("ApartmentBuildingId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("ApartmentManagementSystem.EF.Context.RequestHistory", "Feedback")
                        .WithMany("Files")
                        .HasForeignKey("FeedbackId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("ApartmentManagementSystem.EF.Context.Request", "Request")
                        .WithMany("Files")
                        .HasForeignKey("RequestId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Announcement");

                    b.Navigation("ApartmentBuilding");

                    b.Navigation("Feedback");

                    b.Navigation("Request");
                });

            modelBuilder.Entity("ApartmentManagementSystem.EF.Context.ParkingRegistration", b =>
                {
                    b.HasOne("ApartmentManagementSystem.EF.Context.Apartment", "Apartment")
                        .WithMany("ParkingRegistrations")
                        .HasForeignKey("ApartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Apartment");
                });

            modelBuilder.Entity("ApartmentManagementSystem.EF.Context.QuantityRateConfig", b =>
                {
                    b.HasOne("ApartmentManagementSystem.EF.Context.FeeType", "FeeType")
                        .WithMany("QuantityRateConfigs")
                        .HasForeignKey("FeeTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FeeType");
                });

            modelBuilder.Entity("ApartmentManagementSystem.EF.Context.Request", b =>
                {
                    b.HasOne("ApartmentManagementSystem.EF.Context.ApartmentBuilding", "ApartmentBuilding")
                        .WithMany("Requests")
                        .HasForeignKey("ApartmentBuildingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApartmentBuilding");
                });

            modelBuilder.Entity("ApartmentManagementSystem.EF.Context.RequestHistory", b =>
                {
                    b.HasOne("ApartmentManagementSystem.EF.Context.Request", "Request")
                        .WithMany("RequestHistories")
                        .HasForeignKey("RequestId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Request");
                });

            modelBuilder.Entity("ApartmentManagementSystem.EF.Context.Resident", b =>
                {
                    b.HasOne("ApartmentManagementSystem.EF.Context.ApartmentBuilding", "ApartmentBuilding")
                        .WithMany("Residents")
                        .HasForeignKey("ApartmentBuildingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApartmentBuilding");
                });

            modelBuilder.Entity("ApartmentManagementSystem.EF.Context.UtilityReading", b =>
                {
                    b.HasOne("ApartmentManagementSystem.EF.Context.Apartment", "Apartment")
                        .WithMany("UtilityReadings")
                        .HasForeignKey("ApartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ApartmentManagementSystem.EF.Context.FeeType", "FeeType")
                        .WithMany("UtilityReadings")
                        .HasForeignKey("FeeTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Apartment");

                    b.Navigation("FeeType");
                });

            modelBuilder.Entity("ApartmentManagementSystem.EF.Context.Announcement", b =>
                {
                    b.Navigation("Files");
                });

            modelBuilder.Entity("ApartmentManagementSystem.EF.Context.Apartment", b =>
                {
                    b.Navigation("ApartmentResidents");

                    b.Navigation("FeeNotices");

                    b.Navigation("ParkingRegistrations");

                    b.Navigation("UtilityReadings");
                });

            modelBuilder.Entity("ApartmentManagementSystem.EF.Context.ApartmentBuilding", b =>
                {
                    b.Navigation("Announcements");

                    b.Navigation("Apartments");

                    b.Navigation("BillingCycleSetting")
                        .IsRequired();

                    b.Navigation("FeeTypes");

                    b.Navigation("Files");

                    b.Navigation("Requests");

                    b.Navigation("Residents");
                });

            modelBuilder.Entity("ApartmentManagementSystem.EF.Context.FeeDetail", b =>
                {
                    b.Navigation("FeeDetailTiers");
                });

            modelBuilder.Entity("ApartmentManagementSystem.EF.Context.FeeNotice", b =>
                {
                    b.Navigation("FeeDetails");
                });

            modelBuilder.Entity("ApartmentManagementSystem.EF.Context.FeeRateConfig", b =>
                {
                    b.Navigation("FeeTiers");
                });

            modelBuilder.Entity("ApartmentManagementSystem.EF.Context.FeeType", b =>
                {
                    b.Navigation("FeeDetails");

                    b.Navigation("FeeRateConfigs");

                    b.Navigation("QuantityRateConfigs");

                    b.Navigation("UtilityReadings");
                });

            modelBuilder.Entity("ApartmentManagementSystem.EF.Context.Request", b =>
                {
                    b.Navigation("Files");

                    b.Navigation("RequestHistories");
                });

            modelBuilder.Entity("ApartmentManagementSystem.EF.Context.RequestHistory", b =>
                {
                    b.Navigation("Files");
                });

            modelBuilder.Entity("ApartmentManagementSystem.EF.Context.Resident", b =>
                {
                    b.Navigation("ApartmentResidents");
                });
#pragma warning restore 612, 618
        }
    }
}
